# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-09 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20170725_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionplan',
            name='description',
            field=models.TextField(blank=True, help_text='A description of the goal ofthe plan, e.g. "Gain mass" or "Prepare for summer"', max_length=2000, verbose_name='Description'),
        ),
    ]
