# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-24 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_auto_20170809_1254'),
        ('nutrition', '0003_merge'),
    ]

    operations = [
    ]
