# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-02 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_auto_20170728_0714'),
        ('gym', '0007_auto_20170725_2009'),
    ]

    operations = [
    ]
