# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-28 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170728_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='can_create_via_api',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
