# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-24 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170809_1254'),
        ('core', '0012_merge'),
    ]

    operations = [
    ]
